import datetime

from PyQt6.QtCharts import QPieSlice, QCategoryAxis, QLineSeries, QValueAxis
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QColor, QFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors



class ReportsController:
    def __init__(self, reports_page, mainWindow_controller):
        self.page = reports_page
        self.mainWindow_controller = mainWindow_controller
        self.db = self.mainWindow_controller.db

        self.update_piechart()
        self.update_linegraph()
        self.setup_labels()
        self.generate_full_report_pdf('report.pdf', self.db.reports.get_full_report_data('2025-10-10', '2025-12-10'), ['2025-10-10', '2025-12-10'])

    def setup_labels(self):
        self.page.card1_val.setText(str(self.db.treatments_db.get_treatments_count()))
        self.page.card2_val.setText(str(f'{self.db.reports.get_overall_revenue():,}'))

    def get_payment_method_percentages(self):
        df = self.db.treatments_db.get_service_count()
        total_count = df['count'].sum()
        return [(row['service'], float(row['count']), float(row['count'])/total_count*100 )for _, row in df.iterrows()]

    def update_piechart(self):
        self.page.payments_pie.clear()
        for tag, value, percent in self.get_payment_method_percentages():
            slice_ = QPieSlice(f'{tag}: {percent:.1f}%', value)
            slice_.setLabelVisible(True)
            slice_.setLabel(f'{percent:.1f}%')
            slice_.setLabelColor(QColor.fromRgb(255, 255, 255   ))
            slice_.setLabelFont(QFont('Slate', 7))
            slice_.setLabelPosition(QPieSlice.LabelPosition.LabelInsideHorizontal)
            self.page.payments_pie.append(slice_)

            for marker in self.page.piechart.legend().markers(self.page.payments_pie):
                if marker.slice() is slice_:
                    marker.setLabel(tag)
                    break

    def update_linegraph(self):
        df = self.db.reports.monthly_revenue()
        monthly_revenue = [0] * 12
        for _, row in df.iterrows(): # populate monthly revenue
            month_index = int(row['month']) - 1
            monthly_revenue[month_index] = row['revenue']

        series = QLineSeries()
        series.setName('Revenue')

        for i, revenue in enumerate(monthly_revenue, start=1):
            series.append(i, revenue)
        self.page.linegraph.addSeries(series)

        axis_x = QCategoryAxis()
        axis_x.setTitleText("Month")
        axis_x.setLabelsFont(QFont('Slate', 7))
        months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
        for i, month in enumerate(months, start=1):
            axis_x.append(month, i)
        self.page.linegraph.addAxis(axis_x, Qt.AlignmentFlag.AlignBottom)
        series.attachAxis(axis_x)

        axis_y = QValueAxis()
        axis_y.setTitleText("Amount (PHP)")
        axis_y.setLabelsFont(QFont('Slate', 7))
        self.page.linegraph.addAxis(axis_y, Qt.AlignmentFlag.AlignLeft)
        series.attachAxis(axis_y)

    def refresh_page(self):
        self.update_piechart()
        self.setup_labels()

    def generate_full_report_pdf(self, path, data, date_range):
        doc = SimpleDocTemplate(
            path, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36
        )
        styles = getSampleStyleSheet()
        elements = []

            # Summary report
        elements.append(Paragraph('Clinic Full Report', styles['Title']))
        elements.append(Spacer(1,12))
        elements.append(Paragraph(
            f'Generated by: {self.db.users_db.get_employee_name(self.mainWindow_controller.userid)}, [ID: {self.mainWindow_controller.userid}]',
            styles['Normal']
        ))
        elements.append(Paragraph(
            f'Generated on: {datetime.datetime.now().strftime("%Y/%m/%d %I:%M:%S %p")}',
            styles['Normal']
        ))
        elements.append(Paragraph(
            'Source: AdoraFlow Dental Clinic Management System',
            styles['Normal']
        ))
        elements.append(Paragraph(
            f'Date period: {date_range[0]} - {date_range[1]}',
            styles['Normal']
        ))

        elements.append(Spacer(1,20))

        invoice_summary = data['summary']
        invoice_summary_table = [
            ['Metric', 'Value'],
            ['Total Appointments', invoice_summary['total_appointments']],
            ['Total Treatments', invoice_summary['total_treatments']],
            ['Total Invoices', invoice_summary['total_invoices']],
            ['Total Revenue', f'PHP {invoice_summary["total_revenue"]:,.2f}'],
        ]

        table = Table(invoice_summary_table, colWidths=[200, 200])
        table.hAlign = 'LEFT'
        table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.lightgrey, colors.whitesmoke])
        ]))

        elements.append(Paragraph('Summary', styles['Heading2']))
        elements.append(Spacer(1,10))
        elements.append(table)
        elements.append(Spacer(1,20))

            # Revenue by services report
        elements.append(Paragraph('Revenue by Services', styles['Heading2']))
        elements.append(Spacer(1,10))

        services_table = [['Service', 'Total (PHP)']]
        for row in data['revenue_by_service']:
            services_table.append([row[0], row[1]])

        table = None
        table = Table(services_table, colWidths=[100, 150])
        table.hAlign = 'LEFT'
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.gray),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
        ]))
        elements.append(table)
        elements.append(Spacer(1,20))

            # Appointments by status report
        elements.append(Paragraph('Appointments by Status', styles['Heading2']))
        elements.append(Spacer(1, 10))

        apt_status_table = [['Status', 'Total']]
        for row in data['appointments_by_status']:
            apt_status_table.append([row[0], row[1]])

        table = None
        table = Table(apt_status_table, colWidths=[200, 200])
        table.hAlign = 'LEFT'
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.gray),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
        ]))
        elements.append(table)
        elements.append(Spacer(1,20))

            # Popular services report
        elements.append(Paragraph(' Treatment Service Popularity', styles['Heading2']))
        elements.append(Spacer(1,10))

        popular_services_table = [['Service', 'Total Treatments']]
        for row in data['most_performed_services']:
            popular_services_table.append([row[0], row[1]])

        table = None
        table = Table(popular_services_table, colWidths=[200, 200])
        table.hAlign = 'LEFT'
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.gray),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
        ]))
        elements.append(table)
        elements.append(Spacer(1,20))


        doc.build(elements)